# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle (Fabric 1.19.x - draft release)

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*1.19.x.fabric' # Push events to matching v*1.19.x.fabric

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Install advancecomp
        run: sudo apt-get install advancecomp
      - name: Install strip-nondeterminism
        run: sudo apt-get install strip-nondeterminism
      - name: Install jq
        run: sudo apt-get install jq
      - name: Build with Gradle
        env:
          BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-disabled: true
          arguments: build --scan --stacktrace --warning-mode all
      - name: Submit dependencies to GitHub
        uses: mikepenz/gradle-dependency-submission@v0.8.5
      - name: Rezip mod .jar files to remove directory entries
        run: bash removeDirectoryEntries.sh
      - name: Run strip-nondeterminism on built .jar files
        run: strip-nondeterminism build/libs/*.jar
      - name: Run advzip (-i 9999) on built .jar files
        run: advzip --shrink-insane -kzi 9999 -p build/libs/*.jar
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Draft release ${{ github.ref }}
          body: Replace this text with the description of this release!
          draft: true
          prerelease: false
          files: build/libs/*.jar
